---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'simple'
LeftAndMain:
  extra_requirements_javascript:
    - 'mysite/javascript/googleanalytics.js'
SiteTree:
  nested_urls: true
MySQLDatabase:
  connection_charset: 'utf8'